export const dogBreeds = [
  {
    id: 1,
    name: "Йоркширский терьер",
    imageSrc: "/images/dogs/terier/img.png",
    imageFull: "/images/dogs/terier/img.png",
    country: "Германия / Польша",
    time: "~XVIII-XVIV век",
    weight: "2,3 - 3 кг",
    height: "20 см",
    wool: "Плотная",
    breed: "Игрушка",
    body: "Квадрат",
  },
  {
    id: 2,
    name: "Померанский шпиц",
    imageSrc: "/images/dogs/spic/img.jpg",
    imageFull: "/images/dogs/spic/img.jpg",
    country: "Германия / Польша",
    time: "~XVIII-XVIV век",
    weight: "2,3 - 3 кг",
    height: "20 см",
    wool: "Плотная",
    breed: "Игрушка",
    body: "Квадрат",
  },
  {
    id: 3,
    name: "Немецкая овчарка",
    imageSrc: "/images/dogs/nemec/img.png",
    imageFull: "/images/dogs/nemec/img.png",
    country: "Германия / Польша",
    time: "~XVIII-XVIV век",
    weight: "2,3 - 3 кг",
    height: "20 см",
    wool: "Плотная",
    breed: "Игрушка",
    body: "Квадрат",
  },
  {
    id: 4,
    name: "Корги",
    imageSrc: "/images/dogs/korgu/img.jpg",
    imageFull: "/images/dogs/korgu/img.jpg",
    country: "Германия / Польша",
    time: "~XVIII-XVIV век",
    weight: "2,3 - 3 кг",
    height: "20 см",
    wool: "Плотная",
    breed: "Игрушка",
    body: "Квадрат",
  },
  {
    id: 5,
    name: "Хаски",
    imageSrc: "/images/dogs/hasku/img.jpg",
    imageFull: "/images/dogs/hasku/img.jpg",
    country: "Германия / Польша",
    time: "~XVIII-XVIV век",
    weight: "2,3 - 3 кг",
    height: "20 см",
    wool: "Плотная",
    breed: "Игрушка",
    body: "Квадрат",
  },
];
